name            = "korean-srs"
main            = "worker.js"
compatibility_date = "2026-02-28"

[[d1_databases]]
binding       = "DB"
database_name = "korean-srs-db"
database_id   = "17d29743-2af4-4130-adcf-f8f9acf2cf50"
