name            = "squalie-account"
main            = "worker.js"
compatibility_date = "2026-02-28"

[[d1_databases]]
binding       = "DB"
database_name = "account-db"
database_id   = "bf88a0bb-fd10-4811-a94c-9069fdfd4b5e"
